### ISSUE TITLE
Transcription error marking up equation for leading factor.

### ISSUE THREAD

**Issue by philderbeast** [BlockScope/CIVL-GAP#5]
The equation shown for leading factor in the docs I marked up as

https://github.com/BlockScope/CIVL-GAP/blob/e26334b23531dd8b314d1c32c5304fc4aef2121a/gap.tex#L1264

I perhaps transcribed from the current docs incorrectly because there the equation looks like

    ((LCp - LCmin)/sqrt(LCmin))^(2/3)

I now think that the equation should be

    ((LCp - LCmin)^2/sqrt(LCmin))^(1/3)

This matches the functions I use for plotting leading points, here for a `LCmin` value of 1.25

https://github.com/BlockScope/CIVL-GAP/blob/e26334b23531dd8b314d1c32c5304fc4aef2121a/leading-points.tex#L15

**Comment by joergewald** [comment]
Gap.cs, lines 834ff:
                        double lc_diff = Math.Round(lc - smallest_leading_coefficient, 5, MidpointRounding.AwayFromZero);
                        double slc5 = Math.Pow(smallest_leading_coefficient, 0.5);
                        double tmp = lc_diff / slc5;
                        leading_points = 1 - Math.Pow(tmp, 0.666);
                        if (leading_points < 0) leading_points = 0;
